//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebnayaSemenova.Bases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UchebnayaSemenovaEntities1 : DbContext
    {
        public UchebnayaSemenovaEntities1()
            : base("name=UchebnayaSemenovaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Degree> Degree { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Examen> Examen { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Lectern> Lectern { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Specs> Specs { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
